/**
 * Enum com todos os templates de email disponíveis no sistema
 */
export enum EmailTemplateEnum {
  APROVACAO_DIRETOR = 'APROVACAO_DIRETOR',
  CONFIRMACAO_SOLICITANTE = 'CONFIRMACAO_SOLICITANTE',
  REPROVACAO_SOLICITANTE = 'REPROVACAO_SOLICITANTE',
  APROVADO_SOLICITANTE = 'APROVADO_SOLICITANTE',
  APROVADO_BACKLOG_RH = 'APROVADO_BACKLOG_RH',
}
